<?php

return [
    'admin_local_only' => (bool) env('SYNC360_ADMIN_LOCAL_ONLY', false),
    'host_project_root' => env('SYNC360_HOST_PROJECT_ROOT', base_path()),
    'host_port_probe_host' => env('SYNC360_HOST_PORT_PROBE_HOST', '127.0.0.1'),
    'host_port_probe_timeout_seconds' => (int) env('SYNC360_HOST_PORT_PROBE_TIMEOUT_SECONDS', 1),
    'runtime_root' => env('TENANT_RUNTIME_ROOT', base_path('runtime/tenants')),
    'template_root' => env('TENANT_TEMPLATE_ROOT', base_path('templates/tenant')),
    'infrastructure' => [
        'driver' => env('SYNC360_INFRASTRUCTURE_DRIVER', 'local'),
        'local_docker_compose_bin' => env('SYNC360_LOCAL_DOCKER_COMPOSE_BIN', 'docker compose'),
        'ssh_timeout_seconds' => (int) env('SYNC360_SSH_TIMEOUT_SECONDS', 30),
        'scp_timeout_seconds' => (int) env('SYNC360_SCP_TIMEOUT_SECONDS', 120),
        'ssh_bin' => env('SYNC360_SSH_BIN', 'ssh'),
        'scp_bin' => env('SYNC360_SCP_BIN', 'scp'),
        'sshpass_bin' => env('SYNC360_SSHPASS_BIN', 'sshpass'),
        'ssh_options' => [
            'StrictHostKeyChecking=no',
            'UserKnownHostsFile=/dev/null',
            'ConnectTimeout='.(int) env('SYNC360_SSH_CONNECT_TIMEOUT_SECONDS', 10),
        ],
    ],
    'port_range' => [
        'start' => (int) env('TENANT_PORT_RANGE_START', 4100),
        'end' => (int) env('TENANT_PORT_RANGE_END', 4199),
    ],
    'provisioning' => [
        'driver' => env('TENANT_PROVISIONING_DRIVER', 'openclaw'),
        'fake_delay_seconds' => (int) env('TENANT_PROVISIONING_DELAY_SECONDS', 3),
    ],
    'openclaw' => [
        'image' => env('OPENCLAW_IMAGE', 'ghcr.io/openclaw/openclaw:latest'),
        'service_name' => env('OPENCLAW_SERVICE_NAME', 'openclaw-gateway'),
        'compose_filename' => env('OPENCLAW_COMPOSE_FILENAME', 'compose.yaml'),
        'container_home' => env('OPENCLAW_CONTAINER_HOME', '/home/node/.openclaw'),
        'gateway_port' => (int) env('OPENCLAW_GATEWAY_INTERNAL_PORT', 18789),
        'readiness_path' => env('OPENCLAW_READINESS_PATH', '/readyz'),
        'readiness_timeout_seconds' => (int) env('OPENCLAW_READINESS_TIMEOUT_SECONDS', 45),
        'readiness_poll_interval_ms' => (int) env('OPENCLAW_READINESS_POLL_INTERVAL_MS', 1000),
        'compose_timeout_seconds' => (int) env('OPENCLAW_COMPOSE_TIMEOUT_SECONDS', 600),
    ],
    'workspace_proxy' => [
        'public_readiness_timeout_seconds' => (int) env('SYNC360_WORKSPACE_PUBLIC_READY_TIMEOUT_SECONDS', 120),
        'public_readiness_poll_interval_ms' => (int) env('SYNC360_WORKSPACE_PUBLIC_READY_POLL_INTERVAL_MS', 1500),
    ],
    'workspace_gateway' => [
        'chat_path' => env('SYNC360_WORKSPACE_CHAT_PATH', '/chat'),
        'timeout_seconds' => (int) env('SYNC360_WORKSPACE_CHAT_TIMEOUT_SECONDS', 15),
    ],
    'litellm' => [
        'default_plan_name' => env('LITELLM_DEFAULT_PLAN_NAME', 'trial'),
        'default_budget' => (float) env('LITELLM_DEFAULT_MAX_BUDGET', 25),
        'default_budget_duration' => env('LITELLM_DEFAULT_BUDGET_DURATION', 'monthly'),
        'plan_budgets' => [
            'trial' => (float) env('LITELLM_TRIAL_MAX_BUDGET', env('LITELLM_DEFAULT_MAX_BUDGET', 25)),
            'starter' => (float) env('LITELLM_STARTER_MAX_BUDGET', env('LITELLM_DEFAULT_MAX_BUDGET', 25)),
            'growth' => (float) env('LITELLM_GROWTH_MAX_BUDGET', env('LITELLM_DEFAULT_MAX_BUDGET', 25)),
            'enterprise' => (float) env('LITELLM_ENTERPRISE_MAX_BUDGET', env('LITELLM_DEFAULT_MAX_BUDGET', 25)),
        ],
    ],
    'control_app_deploy' => [
        'enabled' => (bool) env('SYNC360_CONTROL_DEPLOY_ENABLED', false),
        'ssh_host' => env('SYNC360_CONTROL_DEPLOY_SSH_HOST'),
        'ssh_port' => (int) env('SYNC360_CONTROL_DEPLOY_SSH_PORT', 22),
        'ssh_user' => env('SYNC360_CONTROL_DEPLOY_SSH_USER', 'deploy'),
        'ssh_auth_mode' => env('SYNC360_CONTROL_DEPLOY_SSH_AUTH_MODE', 'password'),
        'ssh_password_env_key' => env('SYNC360_CONTROL_DEPLOY_SSH_PASSWORD_ENV_KEY', 'SYNC360_CONTROL_SERVER_SSH_PASSWORD'),
        'repo_path' => env('SYNC360_CONTROL_DEPLOY_REPO_PATH'),
        'branch' => env('SYNC360_CONTROL_DEPLOY_BRANCH', 'codex/control-app-prod-deploy'),
        'compose_file' => env('SYNC360_CONTROL_DEPLOY_COMPOSE_FILE', 'docker-compose.prod.yml'),
        'script_path' => env('SYNC360_CONTROL_DEPLOY_SCRIPT_PATH'),
        'status_file' => env('SYNC360_CONTROL_DEPLOY_STATUS_FILE'),
        'log_file' => env('SYNC360_CONTROL_DEPLOY_LOG_FILE'),
        'log_tail_lines' => (int) env('SYNC360_CONTROL_DEPLOY_LOG_TAIL_LINES', 20),
        'timeout_seconds' => (int) env('SYNC360_CONTROL_DEPLOY_TIMEOUT_SECONDS', 30),
    ],
];
