<?php

return [
    'admin_local_only' => (bool) env('SYNC360_ADMIN_LOCAL_ONLY', false),
    'host_project_root' => env('SYNC360_HOST_PROJECT_ROOT', base_path()),
    'host_port_probe_host' => env('SYNC360_HOST_PORT_PROBE_HOST', '127.0.0.1'),
    'host_port_probe_timeout_seconds' => (int) env('SYNC360_HOST_PORT_PROBE_TIMEOUT_SECONDS', 1),
    'runtime_root' => env('TENANT_RUNTIME_ROOT', base_path('runtime/tenants')),
    'template_root' => env('TENANT_TEMPLATE_ROOT', base_path('templates/tenant')),
    'infrastructure' => [
        'driver' => env('SYNC360_INFRASTRUCTURE_DRIVER', 'local'),
        'local_docker_compose_bin' => env('SYNC360_LOCAL_DOCKER_COMPOSE_BIN', 'docker compose'),
        'ssh_timeout_seconds' => (int) env('SYNC360_SSH_TIMEOUT_SECONDS', 30),
        'scp_timeout_seconds' => (int) env('SYNC360_SCP_TIMEOUT_SECONDS', 120),
        'ssh_bin' => env('SYNC360_SSH_BIN', 'ssh'),
        'scp_bin' => env('SYNC360_SCP_BIN', 'scp'),
        'sshpass_bin' => env('SYNC360_SSHPASS_BIN', 'sshpass'),
        'ssh_options' => [
            'StrictHostKeyChecking=no',
            'UserKnownHostsFile=/dev/null',
            'ConnectTimeout='.(int) env('SYNC360_SSH_CONNECT_TIMEOUT_SECONDS', 10),
        ],
    ],
    'port_range' => [
        'start' => (int) env('TENANT_PORT_RANGE_START', 4100),
        'end' => (int) env('TENANT_PORT_RANGE_END', 4199),
    ],
    'provisioning' => [
        'driver' => env('TENANT_PROVISIONING_DRIVER', 'openclaw'),
        'fake_delay_seconds' => (int) env('TENANT_PROVISIONING_DELAY_SECONDS', 3),
    ],
    'openclaw' => [
        'image' => env('OPENCLAW_IMAGE', 'ghcr.io/openclaw/openclaw:latest'),
        'service_name' => env('OPENCLAW_SERVICE_NAME', 'openclaw-gateway'),
        'compose_filename' => env('OPENCLAW_COMPOSE_FILENAME', 'compose.yaml'),
        'container_home' => env('OPENCLAW_CONTAINER_HOME', '/home/node/.openclaw'),
        'gateway_port' => (int) env('OPENCLAW_GATEWAY_INTERNAL_PORT', 18789),
        'readiness_path' => env('OPENCLAW_READINESS_PATH', '/readyz'),
        'readiness_timeout_seconds' => (int) env('OPENCLAW_READINESS_TIMEOUT_SECONDS', 45),
        'readiness_poll_interval_ms' => (int) env('OPENCLAW_READINESS_POLL_INTERVAL_MS', 1000),
        'compose_timeout_seconds' => (int) env('OPENCLAW_COMPOSE_TIMEOUT_SECONDS', 600),
        'default_agent_model' => env('OPENCLAW_DEFAULT_AGENT_MODEL', 'gpt-4o'),
    ],
    'runtime_capabilities' => [
        'gog' => [
            'id' => 'gog',
            'activation' => 'google_workspace',
            'install_strategy' => 'binary_download',
            'version' => 'v0.12.0',
            'download_url' => 'https://github.com/steipete/gogcli/releases/download/v0.12.0/gogcli_0.12.0_linux_amd64.tar.gz',
            'sha256' => 'a03fccbd67ea2e59a26a56e92de8918577f4bebe4b2f946823419777827cdab2',
            'archive_binary_path' => 'gog',
            'host_install_path' => '/usr/local/bin/gog',
            'container_mounts' => [
                [
                    'source' => '/usr/local/bin/gog',
                    'target' => '/usr/local/bin/gog',
                    'read_only' => true,
                ],
            ],
            'enabled_commands' => [
                'gmail',
                'calendar',
                'drive',
                'contacts',
                'tasks',
                'sheets',
                'docs',
                'slides',
                'people',
                'chat',
                'classroom',
                'forms',
                'appscript',
                'groups',
            ],
            'allowlist_env_key' => 'GOG_ENABLE_COMMANDS',
            'default_account_env_key' => 'GOG_ACCOUNT',
            'env' => [],
            'openclaw_skills' => ['gog'],
            'host_verify_commands' => [
                'test -x {{path}}',
                '{{path}} --version 2>&1 | grep -qF {{version}}',
                '{{path}} --help >/dev/null 2>&1',
            ],
            'container_verify_command' => 'command -v gog >/dev/null 2>&1',
        ],
    ],
    'skill_registry' => [
        'hello-world' => [
            'id' => 'hello-world',
            'label' => 'Hello World (by Sync360)',
            'version' => '1.0.4',
            'description' => 'A simple hello world skill for testing purposes.',
            'runtime_type' => 'sync360_workspace',
            'workspace_files' => [
                'HELLO_WORLD.md',
                'skills/hello-world',
            ],
            'openclaw_skill_ids' => ['hello-world'],
            'default_agent_skill_ids' => ['hello-world'],
            'applicable_industries' => [],
        ],
    ],
    'skill_registry_catalog_version' => 1,
    'skill_catalog' => [
        'enabled' => (bool) env('SYNC360_SKILL_CATALOG_ENABLED', true),
        'scan_enabled' => (bool) env('SYNC360_SKILL_CATALOG_SCAN_ENABLED', true),
        'import_enabled' => (bool) env('SYNC360_SKILL_CATALOG_IMPORT_ENABLED', true),
        'rollout_enabled' => (bool) env('SYNC360_SKILL_CATALOG_ROLLOUT_ENABLED', true),
    ],
    'runtime_customization' => [
        'apply_authorized_user_ids' => array_values(array_filter(array_map('trim', explode(',', (string) env('SYNC360_RUNTIME_CUSTOMIZATION_APPLY_USER_IDS', ''))))),
        'apply_authorized_emails' => array_values(array_filter(array_map('trim', explode(',', (string) env('SYNC360_RUNTIME_CUSTOMIZATION_APPLY_EMAILS', ''))))),
    ],
    'workspace_proxy' => [
        'control_app_upstream' => env('SYNC360_WORKSPACE_CONTROL_APP_UPSTREAM', env('APP_URL', 'http://localhost')),
        'public_readiness_timeout_seconds' => (int) env('SYNC360_WORKSPACE_PUBLIC_READY_TIMEOUT_SECONDS', 120),
        'public_readiness_poll_interval_ms' => (int) env('SYNC360_WORKSPACE_PUBLIC_READY_POLL_INTERVAL_MS', 1500),
    ],
    'workspace_gateway' => [
        'agent_hook_path' => env('SYNC360_WORKSPACE_AGENT_HOOK_PATH', '/hooks/agent'),
        'timeout_seconds' => (int) env('SYNC360_WORKSPACE_CHAT_TIMEOUT_SECONDS', 15),
    ],
    'litellm' => [
        'default_plan_name' => env('LITELLM_DEFAULT_PLAN_NAME', 'trial'),
        'default_budget' => (float) env('LITELLM_DEFAULT_MAX_BUDGET', 25),
        'default_budget_duration' => env('LITELLM_DEFAULT_BUDGET_DURATION', 'monthly'),
        'team_id' => env('LITELLM_TEAM_ID'),
        'default_models' => array_filter(array_map('trim', explode(',', (string) env('LITELLM_DEFAULT_MODELS', 'gpt-4o')))),
        'plan_budgets' => [
            'trial' => (float) env('LITELLM_TRIAL_MAX_BUDGET', env('LITELLM_DEFAULT_MAX_BUDGET', 25)),
            'starter' => (float) env('LITELLM_STARTER_MAX_BUDGET', env('LITELLM_DEFAULT_MAX_BUDGET', 25)),
            'growth' => (float) env('LITELLM_GROWTH_MAX_BUDGET', env('LITELLM_DEFAULT_MAX_BUDGET', 25)),
            'enterprise' => (float) env('LITELLM_ENTERPRISE_MAX_BUDGET', env('LITELLM_DEFAULT_MAX_BUDGET', 25)),
        ],
    ],
    'control_app_deploy' => [
        'enabled' => (bool) env('SYNC360_CONTROL_DEPLOY_ENABLED', false),
        'ssh_host' => env('SYNC360_CONTROL_DEPLOY_SSH_HOST'),
        'ssh_port' => (int) env('SYNC360_CONTROL_DEPLOY_SSH_PORT', 22),
        'ssh_user' => env('SYNC360_CONTROL_DEPLOY_SSH_USER', 'deploy'),
        'ssh_auth_mode' => env('SYNC360_CONTROL_DEPLOY_SSH_AUTH_MODE', 'password'),
        'ssh_password_env_key' => env('SYNC360_CONTROL_DEPLOY_SSH_PASSWORD_ENV_KEY', 'SYNC360_CONTROL_SERVER_SSH_PASSWORD'),
        'repo_path' => env('SYNC360_CONTROL_DEPLOY_REPO_PATH'),
        'branch' => env('SYNC360_CONTROL_DEPLOY_BRANCH', 'codex/control-app-prod-deploy'),
        'compose_file' => env('SYNC360_CONTROL_DEPLOY_COMPOSE_FILE', 'docker-compose.prod.yml'),
        'script_path' => env('SYNC360_CONTROL_DEPLOY_SCRIPT_PATH'),
        'status_file' => env('SYNC360_CONTROL_DEPLOY_STATUS_FILE'),
        'log_file' => env('SYNC360_CONTROL_DEPLOY_LOG_FILE'),
        'log_tail_lines' => (int) env('SYNC360_CONTROL_DEPLOY_LOG_TAIL_LINES', 20),
        'timeout_seconds' => (int) env('SYNC360_CONTROL_DEPLOY_TIMEOUT_SECONDS', 30),
    ],

    // ── Conversations ──────────────────────────────────────────────────────────
    // Set SYNC360_REFRESH_SUMMARIES=true for one deploy cycle to clear and
    // regenerate all existing AI session summaries with the current prompt.
    // Flip back to false (or remove) after the next scheduler run completes.
    'refresh_summaries' => (bool) env('SYNC360_REFRESH_SUMMARIES', false),
];
